# Basic Questions (10)

#1.List all phone brands and models.
SELECT brand, model
FROM phones;

#2.Find all phone models released in the release_year 2024.
SELECT model
FROM phones
WHERE release_year = 2024;

#3.List all countries in the 'Europe' continent.
SELECT country
FROM regions
WHERE continent = 'Europe';

#4.Find all sales where more than 5,000 units_sold.
SELECT *
FROM sales
WHERE units_sold > 5000;

#5.List all phone models made by 'Google'.
SELECT model
FROM phones
WHERE brand = 'Google';

#6.How many regions (countries) are in the regions table?
SELECT COUNT(*) AS total_regions
FROM regions;

#7.What is the average base_price_usd of all phones?
SELECT AVG(base_price_usd) AS avg_price
FROM phones;

#8.Find all sales that occurred on '2024-03-01'.
SELECT *
FROM sales
WHERE sale_date = '2024-03-01';

#9.List all phones with storage_gb of 512, ordered by price (highest first).
SELECT *
FROM phones
WHERE storage_gb = 512
ORDER BY base_price_usd DESC;

#10.What is the total number of units_sold across all recorded sales?
SELECT SUM(units_sold) AS total_units_sold
FROM sales;

###

# Intermediate Questions (15)

#1. List the model name, country, and units_sold for every sale.
SELECT p.model, r.country, s.units_sold
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
JOIN regions r ON s.region_id = r.region_id;

#2. What is the total revenue (units_sold * sale_price_per_unit_usd) for sale_id 'S10005'?
SELECT sale_id,
       units_sold * sale_price_per_unit_usd AS total_revenue
FROM sales
WHERE sale_id = 'S10005';

#3. How many total units has each brand sold?
SELECT p.brand, SUM(s.units_sold) AS total_units_sold
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
GROUP BY p.brand;

#4. What is the total number of units sold in each continent?
SELECT r.continent, SUM(s.units_sold) AS total_units_sold
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.continent;

#5. List the brand, model, and sale_date for all sales that happened in 'India'.
SELECT p.brand, p.model, s.sale_date
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
JOIN regions r ON s.region_id = r.region_id
WHERE r.country = 'India';

#6. Find the average sale_price_per_unit_usd for the 'iPhone 15 Pro' (model) across all regions.
SELECT AVG(s.sale_price_per_unit_usd) AS avg_sale_price
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
WHERE p.model = 'iPhone 15 Pro';

#7. List all phone models (by name) that have not yet been sold.
SELECT p.model
FROM phones p
LEFT JOIN sales s ON p.phone_id = s.phone_id
WHERE s.phone_id IS NULL;

#8. What is the total revenue (units_sold * sale_price_per_unit_usd) generated by each country?
SELECT r.country,
       SUM(s.units_sold * s.sale_price_per_unit_usd) AS total_revenue
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.country;

#9. Find all sales where the sale_price_per_unit_usd was higher than the phone's base_price_usd.
SELECT s.*
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
WHERE s.sale_price_per_unit_usd > p.base_price_usd;

#10. Which main_distributor is responsible for the most units_sold?
SELECT r.main_distributor,
       SUM(s.units_sold) AS total_units_sold
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.main_distributor
ORDER BY total_units_sold DESC
LIMIT 1;

#11. List all countries in 'Asia' that have had at least one sale.
SELECT DISTINCT r.country
FROM sales s
JOIN regions r ON s.region_id = r.region_id
WHERE r.continent = 'Asia';

#12. What is the most expensive phone (by base_price_usd) sold in 'Germany'?
SELECT p.brand, p.model, p.base_price_usd
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
JOIN regions r ON s.region_id = r.region_id
WHERE r.country = 'Germany'
ORDER BY p.base_price_usd DESC
LIMIT 1;

#13. How many 'Apple' phones (by units_sold) were sold in 'North America'?
SELECT SUM(s.units_sold) AS total_units_sold
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
JOIN regions r ON s.region_id = r.region_id
WHERE p.brand = 'Apple'
  AND r.continent = 'North America';

#14. List all countries and the total number of sales transactions they have.
SELECT r.country, COUNT(*) AS total_sales
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.country;

#15. Find the average units_sold per sale for each brand.
SELECT p.brand, AVG(s.units_sold) AS avg_units_sold
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
GROUP BY p.brand;

###

#Advanced Questions (15)

#1.Rank countries within each continent based on their total revenue (highest first).
SELECT
    r.continent,
    r.country,
    SUM(s.units_sold * s.sale_price_per_unit_usd) AS total_revenue,
    RANK() OVER (
        PARTITION BY r.continent
        ORDER BY SUM(s.units_sold * s.sale_price_per_unit_usd) DESC
    ) AS revenue_rank
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.continent, r.country;

 
#2.[CTE] Using a Common Table Expression, find the top 3 phone brands that have generated the most revenue globally.
WITH brand_revenue AS (
    SELECT 
        p.brand,
        SUM(s.units_sold * s.sale_price_per_unit_usd) AS total_revenue
    FROM sales s
    JOIN phones p ON s.phone_id = p.phone_id
    GROUP BY p.brand
)
SELECT *
FROM brand_revenue
ORDER BY total_revenue DESC
LIMIT 3;

#3.List all sales where the units_sold were higher than the average units_sold for that specific phone_id.
SELECT *
FROM sales s
WHERE s.units_sold > (
    SELECT AVG(units_sold)
    FROM sales
    WHERE phone_id = s.phone_id # Only calculate the average units_sold for the SAME phone_id as the current row in the outer query.
);

#4.Calculate the 7-day rolling average of total units_sold.
SELECT
    sale_date,
    SUM(units_sold) AS total_units,
    AVG(SUM(units_sold)) OVER (
        ORDER BY sale_date
        ROWS 6 PRECEDING
    ) AS rolling_7_day_avg
FROM sales
GROUP BY sale_date
ORDER BY sale_date;

#5.Find the "market share" (by units_sold) for each brand within 'Europe'.
SELECT 
	p.brand,
	sum(s.units_sold) as brand_units,
    ROUND(
		sum(s.units_sold)/
        (SELECT sum(ss.units_sold)
        FROM sales ss
        JOIN regions rr ON ss.region_id = rr.region_id
        WHERE rr.continent = 'Europe'
        ) * 100, 2) as market_share_percent
FROM sales s
JOIN regions r ON s.region_id = r.region_id
JOIN phones p ON s.phone_id = p.phone_id
WHERE r.continent = 'Europe'
GROUP BY p.brand
ORDER BY market_share_percent DESC;

#6.For each brand, find the phone model that contributed the most to its total revenue.
WITH brand_model_revenue AS (
    SELECT
        p.brand,
        p.model,
        SUM(s.units_sold * s.sale_price_per_unit_usd) AS revenue,
        RANK() OVER (
            PARTITION BY p.brand
            ORDER BY SUM(s.units_sold * s.sale_price_per_unit_usd) DESC
        ) AS rnk
    FROM sales s
    JOIN phones p ON s.phone_id = p.phone_id
    GROUP BY p.brand, p.model
)
SELECT brand, model, revenue
FROM brand_model_revenue
WHERE rnk = 1
ORDER BY brand;

#7.Find the country that has sold the most 'Samsung' phones (by units_sold).
SELECT r.country
FROM sales s
JOIN regions r ON s.region_id = r.region_id
JOIN phones p ON s.phone_id = p.phone_id
WHERE p.brand = 'Samsung'
GROUP BY r.country
ORDER BY sum(s.units_sold) DESC
LIMIT 1;

#8.For each sale, show the sale_id, country, units_sold, and the average units_sold for that country in a separate column.
SELECT 
    s.sale_id,
    r.country,
    s.units_sold,
    AVG(s.units_sold) OVER (PARTITION BY r.country) AS avg_units_sold_country
FROM sales s
JOIN regions r ON s.region_id = r.region_id;

#9.Identify "premium" phones (base price > $1000). Then, find out which continent sold the most "premium" phones.
SELECT r.continent, SUM(s.units_sold) AS premium_units
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
JOIN regions r ON s.region_id = r.region_id
WHERE p.base_price_usd > 1000
GROUP BY r.continent
ORDER BY premium_units DESC
LIMIT 1;

#10.Find the month-over-month revenue growth rate for the 'USA'. (Hint: Use LAG).
SELECT
    DATE_FORMAT(sale_date, '%Y-%m') AS month,
    SUM(units_sold * sale_price_per_unit_usd) AS revenue,
    (SUM(units_sold * sale_price_per_unit_usd) 
     - LAG(SUM(units_sold * sale_price_per_unit_usd)) OVER (ORDER BY DATE_FORMAT(sale_date, '%Y-%m')))
     / LAG(SUM(units_sold * sale_price_per_unit_usd)) OVER (ORDER BY DATE_FORMAT(sale_date, '%Y-%m'))
     AS growth_rate
FROM sales s
JOIN regions r ON s.region_id = r.region_id
WHERE r.country = 'USA'
GROUP BY month
ORDER BY month;

#11.Find the brand with the highest number of units_sold in the country with the lowest number of units_sold.
SELECT p.brand, SUM(s.units_sold) AS brand_units
FROM sales s
JOIN regions r ON s.region_id = r.region_id
JOIN phones p ON s.phone_id = p.phone_id
WHERE r.country = (
    SELECT country
    FROM sales s2
    JOIN regions r2 ON s2.region_id = r2.region_id
    GROUP BY country
    ORDER BY SUM(s2.units_sold) #country with the lowest number of unets_sold
    LIMIT 1
)
GROUP BY p.brand
ORDER BY brand_units DESC #the highest number of units_sold
LIMIT 1;

#12.List all phone models that were sold in every continent.
SELECT p.model
FROM phones p
JOIN sales s ON p.phone_id = s.phone_id
JOIN regions r ON s.region_id = r.region_id
GROUP BY p.model
HAVING COUNT(DISTINCT r.continent) = (
    SELECT COUNT(DISTINCT continent) FROM regions
);
#There is no model that was sold in every continent

#13.Find the top 3 best-selling phone models (by units_sold) for each continent.
SELECT continent, model, total_units
FROM (
    SELECT 
        r.continent,
        p.model,
        SUM(s.units_sold) AS total_units,
        DENSE_RANK() OVER (PARTITION BY r.continent ORDER BY SUM(s.units_sold) DESC) AS rk
    FROM sales s
    JOIN phones p ON s.phone_id = p.phone_id
    JOIN regions r ON s.region_id = r.region_id
    GROUP BY r.continent, p.model
) t
WHERE rk <= 3
ORDER BY continent, total_units DESC;

#14.Calculate the total revenue for each brand, but only include sales where the sale_price_per_unit_usd was at least 10% above the base_price_usd.
SELECT p.brand, 
       SUM(s.units_sold * s.sale_price_per_unit_usd) AS total_revenue
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
WHERE s.sale_price_per_unit_usd >= 1.1 * p.base_price_usd
GROUP BY p.brand
ORDER BY total_revenue DESC;
# none was returnd because none of the sales in the data are actually ≥ 10% above the base price.

#15.Categorize phones by base_price_usd: 'Budget' (<500), 'Mid-range' (500-900), 'Premium' (>900). Then find the total units_sold for each category.
SELECT 
    CASE 
        WHEN p.base_price_usd < 500 THEN 'Budget'
        WHEN p.base_price_usd BETWEEN 500 AND 900 THEN 'Mid-range'
        ELSE 'Premium'
    END AS price_category,
    SUM(s.units_sold) AS total_units_sold
FROM phones p
JOIN sales s ON p.phone_id = s.phone_id
GROUP BY price_category
ORDER BY total_units_sold DESC;

###

#Critical thinking/One on One 

#1.Student should prepare 1 basic question for the given data set (intermediate or advance level) and answer. 
#Q: Which phone brand has the most models available in the dataset?
SELECT brand, COUNT(*) AS model_count
FROM phones
GROUP BY brand
ORDER BY model_count DESC
LIMIT 1;
#A: Samsung has the most diverse products

#2.Student should prepare 1 intermediate level question for the given data set (intermediate or advance level) and answer. 
#Q: Which region has the highest average units_sold per sale?
SELECT r.country, AVG(s.units_sold) AS avg_units
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.country
ORDER BY avg_units DESC
LIMIT 1;
#A: China is where sales are most concentrated, which may indicate strong high demand markets.

#3.Student should prepare 1 intermediate level question for the given data set (intermediate or advance level) and answer. 
#Q: Which phone model has generated the highest total revenue?
SELECT p.model, 
SUM(s.units_sold * s.sale_price_per_unit_usd) AS revenue
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
GROUP BY p.model
ORDER BY revenue DESC
LIMIT 1;
#A: Galaxy S24 is the key revenue driver for the company, helping focus promotions or production priorities

#4.Student should prepare 1 intermediate level question for the given data set (intermediate or advance level) and answer. 
#Q: Which brand sells the largest phones on average (by storage_gb)?
SELECT brand, AVG(storage_gb) AS avg_storage
FROM phones
GROUP BY brand
ORDER BY avg_storage DESC
LIMIT 1;
#A: OnePlus is the brand that offer larger storage devices

#5. Students should prepare 1 advanced level question for the given data set (intermediate or advance level) and answer. 
#Q: Which country has the highest revenue per unit sold (average sale price)?
SELECT r.country, 
SUM(s.units_sold * s.sale_price_per_unit_usd)/SUM(s.units_sold) AS avg_price
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.country
ORDER BY avg_price DESC
LIMIT 1;
#A: UAE customers pay more per phone, revealing regions where premium pricing works best

#Q6: Most expensive phone brand overall
SELECT brand, AVG(base_price_usd) AS avg_price
FROM phones
GROUP BY brand
ORDER BY avg_price DESC;
#A: Sony

#Q7: Brand that sells the most units overall
SELECT p.brand, SUM(s.units_sold) AS total_units_sold
FROM sales s
JOIN phones p ON s.phone_id = p.phone_id
GROUP BY p.brand
ORDER BY total_units_sold DESC;
#A: Samsung

#Q8: Which continent generates the highest revenue?
SELECT 
    r.continent,
    SUM(s.units_sold * s.sale_price_per_unit_usd) AS total_revenue
FROM sales s
JOIN regions r ON s.region_id = r.region_id
GROUP BY r.continent
ORDER BY total_revenue DESC
LIMIT 1;
#A: Asia


